# SPDX-FileCopyrightText: 2025 2025 Fundament Software SPC <https://fundament.software>
#
# SPDX-License-Identifier: Apache-2.0

version = 2

# generated files
[[annotations]]
path = [
    "Cargo.lock",
		"flake.lock",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
